<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ReservasFlags extends Model
{
    use HasFactory;
    protected $fillable = [
        'referencia',
        'referencia_data',
        'ativo',
        'idreserva',
        'data_criacao_reserva',
        'empreendimento',
        'idempreendimento',
        'bloco',
        'unidade',
        'idunidade',
        'cliente',
        'idcliente',
        'corretor',
        'idcorretor',
        'flag_inicio',
        'data_flag_inicio',
        'flag_inicio_semproposta',
        'data_flag_inicio_semproposta',
        'flag_vencida',
        'data_flag_vencida',
        'flag_vendida',
        'data_flag_vendida',
        'flag_distrato',
        'data_flag_distrato',
        'flag_analisada',
        'data_flag_analisada',
        'flag_aprovada',
        'data_flag_aprovada',
        'flag_aprovada_comercial',
        'data_flag_aprovada_comercial',
        'flag_vender_sienge',
        'data_flag_vender_sienge',
        'flag_cancelada_sienge',
        'data_flag_pode_faturar',
        'flag_documentos',
        'data_flag_documentos',
        'flag_contrato',
        'data_flag_contrato',
        'flag_aguardando_faturamento',
        'data_flag_aguardando_faturamento',
        'flag_faturada',
        'data_flag_faturada',
        'flag_pendente_assinatura_eletronica',
        'data_flag_pendente_assinatura_eletronica',
        'flag_pendente_assinatura_eletronica_segundo_envelope',
        'data_flag_pendente_assinuatura_eletr_seg_env',
        'flag_assinatura_clientes_associados',
        'data_flag_assinatura_clientes_associados',
        'flag_assinatura_todas_partes',
        'data_flag_assinatura_todas_partes',
        'flag_reprovada_comercial',
        'data_flag_reprovada_comercial',
        'flag_pendente_comercial',
        'data_flag_pendente_comercial',
        'flag_devolucao_erp',
        'data_flag_devolucao_erp',
        'clientes_id',
    ];
}
